extraction:
  cpp:
    after_prepare: 
      - python report.py 7
  cobol:
    after_prepare: 
      - python report.py 7
  csharp:
    after_prepare: 
      - python report.py 7
  java:
    after_prepare: 
      - python report.py 7
  javascript:
    after_prepare: 
      - python report.py 7
  python:
    after_prepare: 
      - python report.py 7
